<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>config</string>
		<string>conf</string>
	</array>
	<key>name</key>
	<string>OpenBSD Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(\$)[a-zA-Z_]\w*</string>
			<key>name</key>
			<string>variable.other.openbsd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;[a-zA-Z_]+&gt;</string>
			<key>name</key>
			<string>variable.other.openbsd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(\/[0-9]{1,2})?)(?!-)\b</string>
			<key>name</key>
			<string>constant.numeric.ip.openbsd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)([a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2})(?!-)\b</string>
			<key>name</key>
			<string>constant.numeric.ethernet.openbsd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)([0-9]+(\.[0-9]+)?)(?!-)\b</string>
			<key>name</key>
			<string>constant.numeric.openbsd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\!|:|=|\\|;)</string>
			<key>name</key>
			<string>keyword.operator.openbsd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;&gt;|&lt;|&gt;|&lt;=|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.openbsd</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.openbsd</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.openbsd</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.openbsd</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.openbsd</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.openbsd</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.openbsd</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.openbsd</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.openbsd</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.openbsd</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.openbsd</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.config</string>
	<key>uuid</key>
	<string>C27C0C41-A748-445F-9CBD-8E5E0DC2548F</string>
</dict>
</plist>
