<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pf.config</string>
	</array>
	<key>name</key>
	<string>OpenBSD PF Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(anchor|quick|on|proto|on|received-on|port|set|table|const|icmp-type)(?!-)\b</string>
			<key>name</key>
			<string>keyword.control.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(in|out|udp|tcp|any|no-route|inet|icmp|all|esp|ipencap)(?!-)\b</string>
			<key>name</key>
			<string>constant.language.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(pass|block|match|drop|to|from|rdr-to|nat-to)(?!-)\b</string>
			<key>name</key>
			<string>support.function.kernel.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$)[a-zA-Z_]\w*</string>
			<key>name</key>
			<string>variable.language.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;[a-zA-Z_]+&gt;</string>
			<key>name</key>
			<string>variable.language.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(\/[0-9]{1,2})?)(?!-)\b</string>
			<key>name</key>
			<string>constant.numeric.ip.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)([a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2}\:[a-fA-f0-9]{1,2})(?!-)\b</string>
			<key>name</key>
			<string>constant.numeric.ethernet.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)([0-9]+(\.[0-9]+)?)(?!-)\b</string>
			<key>name</key>
			<string>constant.numeric.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\!|:|=|\\|;)</string>
			<key>name</key>
			<string>keyword.operator.pf</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;&gt;|&lt;|&gt;|&lt;=|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.pf</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.pf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.pf</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.pf</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.pf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.pf</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.pf</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pf</string>
	<key>uuid</key>
	<string>5FAA3C93-3D00-44A2-B341-B597FD484563</string>
</dict>
</plist>
